Fix test logs
ooipy/ooipy pull request #80
Opened 2021-07-21 22:59 UTC by Molkree

Fixes #76

[Example run](https://github.com/Molkree/ooipy/actions/runs/1054273728)
![image](https://user-images.githubusercontent.com/12860284/126570399-17c1be13-2e1b-47b1-ba46-de53a44705b9.png)

2021-07-26 19:37 UTC, John-Ragland requested changes
There's an error with versioning that we've fixed in other PRs but it hasn't made it's way all the way to the main branch yet. 

in line 13 of flake8.yml change to:
`python-version: 3.7.11`

This will probably be an issue with all other PRs as well

2021-07-26 19:47 UTC, Molkree commented
@John-Ragland, that's one of the reasons I suggested to just drop this flake8 workflow ;) #72 
It's also not the first time it breaks for you! 1546537

I'll go ahead and update [setup-python](https://github.com/actions/setup-python) Action to v2 because it can download specific Python versions that are not preinstalled. But at the same time I will unpin Python patch version to just use latest, and will also drop `x64` as it is default now.

2021-07-28 17:27 UTC, lsetiawan approved these changes
@Molkree Thanks again for your contributions. Could you rebase this PR with the current development branch? Thanks!

2021-07-29 19:27 UTC, John-Ragland approved these changes

2021-07-29 19:27 UTC, merged