Add citation file
ooipy/ooipy pull request #95
Opened 2021-08-24 17:02 UTC by FelixSchwock

Resolves issue #94

2021-08-25 16:22 UTC, John-Ragland approved these changes

2021-09-09 21:48 UTC, Molkree requested changes
File extension should be `.cff`, other than that looks good.

2021-09-27 17:10 UTC, Molkree requested changes

2021-09-27 17:10 UTC, Molkree commented on CITATION.ccf
> +ccf-version: 1.2.0
and inside the file too, @FelixSchwock 
```suggestion
cff-version: 1.2.0
```

2021-09-27 17:16 UTC, Molkree requested changes

2021-09-27 17:16 UTC, Molkree commented on CITATION.cff
> +ccf-version: 1.2.0
and inside the file too, @FelixSchwock 
```suggestion
cff-version: 1.2.0
```

2021-09-27 17:36 UTC, FelixSchwock commented on CITATION.cff
> +ccf-version: 1.2.0
Ah thank you, I missed that.

2021-09-27 17:43 UTC, Molkree approved these changes

2021-09-30 18:52 UTC, merged